config/routes.rb
Rails.application.routes.draw do
  resources :texts
  resources :inbounds
  resources :contacts do
    resources :texts
  end

  root to: 'texts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

end

app/models/inbound.rb
class Inbound < ActiveRecord::Base

end

app/models/text.rb
class Text < ActiveRecord::Base
  # before_create :send_text_message
#
private
#   def send_sms
#     resposne = RestClient::Request.new(
#       method: :post,
#       url:
#       user:
#       password:
#       payload: {
#         Body: body,
#         From: from,
#         To: to
#       }.execute
#     )
#   end

# def send_text_message
#   # number_to_send_to = params[number_to_send_to]
#
#   twilio_sid = "PNc027046aec87348e8dd94ee7e9d27d55"
#   twilio_token = "e67d005d04108d0e09e707a1f6ec6f63"
#   twilio_phone_number ="+15005550006"
#
#   @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
#   @twilio_client.account.sms.messages.create(
#   from: "5033749324",
#   to: "5035474491",
#   body: "Test Message from testing"
#   )
# end
#
# def number_to_send_to
#   params.require(:text).permit(:to_number)
# end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/webhookable.rb
# module Webhookable
#   extend ActiveSupport::Concern
#
#   def set_header
#     response.headers["Content-Type"] = "text/xml"
#   end
#
#   def render_twiml(response)
#     render text: response.text
#   end
#
# end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path
    else
      render new
    end
  end

  def show
    @contact = Contact.find(params[:id])
    @text = Text.new
  end

  def update
    @contact = Contact.find(params[:id])
    @text = Text.create(number_to_send_to)
    twilio_sid = "ACae2ec4ec4b2f7d01251c2be94964ff7e"
    twilio_token = "e67d005d04108d0e09e707a1f6ec6f63"
    twilio_phone_number ="+15033749324"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @twilio_client.account.sms.messages.create(
    from: twilio_phone_number,
    to: "+1#{@contact.number}",
    body: "#{@text.body}"
    )
    redirect_to contact_path(@contact)
  end

private

  def contact_params
    params.require(:contact).permit(:name, :number)
  end

  def number_to_send_to
    params.require(:text).permit(:to_number, :body)
  end
end

app/controllers/inbounds_controller.rb
class InboundsController < ApplicationController
  def index
    @body = params[:Body]
    @from_number = params[:From]
    render 'index.xml.erb', content_type: 'text/xml'
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @texts = Text.all
    message_body = params["Body"]
    from_number = params["From"]

  end

  def new
    @text = Text.new
    @contacts = Contact.all
  end


  def create
    twilio_sid = "ACae2ec4ec4b2f7d01251c2be94964ff7e"
    twilio_token = "e67d005d04108d0e09e707a1f6ec6f63"
    twilio_phone_number ="+15033749324"
    all_messages = []
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    messages = messages_params(params)
    messages.each do |key, value|
      @twilio_client.account.sms.messages.create(
      from: twilio_phone_number,
      to: value,
      body: params[:text].first.at(1)
      )
      text = Text.create(number_to_send_to)
      to_number = "+1" + value
      body = params[:text].first.at(1)
    end
    #
    # @text = Text.create(number_to_send_to)
    # to_number = "+1" + @text.to_number
    # body = @text.body

    redirect_to texts_path
  end

  def messages_params(params)
    @messages = params.flatten.slice(4..(params.flatten.length - 9))
    @messages = Hash[*@messages]
    return @messages
  end

  # def send_text_message
  #   number_to_send_to = params[:number_to_send_to]
  #
  #   twilio_sid = "AC52afaf4420645a8cdb686fd6ce111062"
  #   twilio_token = "392ec8487afaaf7ad7a2deb65b8adb55"
  #   twilio_phone_number ="+15005550006"
  #
  #   @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
  #   @twilio_client.account.sms.messages.create(
  #   from: "#{twilio_phone_number}",
  #   to: number_to_send_to,
  #   body: "Test Message from testing"
  #   )
  # end

  private


    def number_to_send_to
      params.require(:text).permit(:to_number, :body)
    end

end


# 5033749324

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_new.html.erb
<h1>Contact Creation Form</h1>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit "Add Contact" %>
<% end %>

app/views/contacts/index.html.erb
<h2>Contacts Index Page</h2>

<%= link_to "Text List", texts_path %>

<% if @contacts.any? %>

  <h3>Contacts sent so far</h3>
  <ul>
    <% @contacts.each do |contact| %>
      <li><%= link_to contact.name, contact_path(contact) %></li>
      <li><%= contact.number %></li>
    <% end %>
  </ul>
<% else %>
  <p>No contacts have been created!</p>
<% end %>

<%= link_to "Add a contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1>Contact Creation Form</h1>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit "Add Contact" %>
<% end %>

app/views/contacts/show.html.erb
<h3>Contact info for <%= @contact.name %></h3>

<p><%= @contact.number %></p>

<h3>You wanna send this person a text? Huh? Yeah?</h3>

<h1>Text Creation Form</h1>

<%= form_for @text do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.hidden_field :to_number, :value => @contact.number %>
  <%= f.submit "Send Text" %>
<% end %>

<%= link_to "Back To Contacts List", contacts_path %>

app/views/inbounds/index.xml.erb
<Response>
<Sms>Thanks for the text <%= @from_number %>! You said: <%= @body %></Sms>
</Response>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/texts/index.html.erb
<h1>Texting App Index Page</h1>

<%= link_to "Contacts List", contacts_path %>

<% if @texts.any? %>

  <h3>Texts sent so far</h3>
  <ul>
    <% @texts.each do |text| %>
      <li><%= text.to_number %></li>
      <li><%= text.body %></li>
    <% end %>
  </ul>
<% else %>
  <p>No texts have been sent/received yet.</p>
<% end %>

<%= link_to "Send a Text", new_text_path %>
<br>
<%= link_to "Add a contact", new_contact_path %>

app/views/texts/new.html.erb
<h1>Text Creation Form</h1>

<%= form_for @text do |f| %>
  <%= f.label :to_number %>
  <%= f.text_field :to_number %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Send Text" %>
<% end %>

<br>

<hr>

<br>

<%= form_for @text do |f| %>
  <% @contacts.each do |contact| %>
    <input type="checkbox" name=<%= contact.id %> value=<%= contact.number %>><%= contact.name %>
    <br>
  <% end %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br>
  <%= f.submit "Send Texts" %>
<% end %>